server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/..."
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
jwt:
  signerKey: "QCOGxKQiUbQ8hmsDIe251lAtmbaImiSaKevg6NLyquqKGUD7SPwYVD8DjTlzBrBW"