spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/tour_management"
    username: root
    password:  # Store this in an environment variable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 442264654014-773n7goeub6omj2nchtvrhjd0rsf4ndn.apps.googleusercontent.com
#            client-secret: ${GOOGLE_CLIENT_SECRET}  # Store this in an environment variable
#            scope: profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Google
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
#            user-name-attribute: sub

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
