spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/tour_management"
    username: root
    password:  # Store this in an environment variable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp  # Đã sửa từ `stmp` thành `smtp`
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

outbound:
  identity:
    client-id: "${GOOGLE_CLIENT_ID}"
    client-secret: "${GOOGLE_CLIENT_SECRET}"
    redirect-uri: "http://localhost:8080/api/login/oauth2/google"
    scope: spring.security.oauth2.client.registration.google.scope=openid,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile

feign:
  client:
    config:
      SSOG:
        connect-timeout: 5000
        read-timeout: 5000

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
